services:
  - type: web
    name: reply-coach-ai-backend
    runtime: node
    plan: starter
    branch: main
    buildCommand: npm install
    startCommand: node server.js

    envVarGroups:
      - Reply-Coach-Ai_Secrets

    envVars:
      - key: APP_URL
        value: https://reply-coach-ai-backend.onrender.com
